name: LAO
favicon: null
layout_spectrum: 0.35916237346827984
typography_spectrum: 0.8717897180467844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.29934216057881713
  lightness: 0.18977268040180206
  saturation: 0.42451993096619844
  rhythmicContrast: 0.05351703125052154
purpose: []
